### ISSUE TITLE
The CI gets run twice when using this

### ISSUE THREAD

**Issue by futurelucas4502** [samuelmeuli/action-electron-builder#23]
I believe this is because we are running `git push && git push --tags` resulting in the function being called twice:
https://github.com/marketplace/actions/electron-builder-action#releasing (step 4)

**Comment by futurelucas4502** [comment]
Obvious not a huge issue if you set up what branches to use however it could be useful to provide some documentation on how to do that for newbies

**Comment by samuelmeuli** [comment]
That's the expected behavior, GitHub Actions executed your workflow once for the pushed commit and once for the pushed tag. This is not related to this action, have a look at the [GitHub Actions docs](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on) if you'd like to configure your workflow differently.

**Comment by hodgef** [comment]
To prevent the CI being from run twice you can add this to your workflow:

```
on:
  push:
    tags:
      - v*
```
