### ISSUE TITLE
App build work, but artifacts are not publishing

### ISSUE THREAD

**Issue by vitalykarasik** [samuelmeuli/action-electron-builder#6]
Thank you for your great project!
I cloned your mini-diary repo and played with builds. Build action is triggered, build is OK, but artifacts are not publishing.
As far as I understand from your documentation, build action is publishing by default. Am I wrong?
When I run build manually on my MacOS, 'yarn build' builds app, and 'electron-builder build --mac --win --publish always' builds and publishes.

Thank you again,
Vitaly

**Comment by samuelmeuli** [comment]
Hi Vitaly,

By default, the action [won't create a release](https://github.com/samuelmeuli/action-electron-builder/blob/86c5099b7a3b82d6ceae02d64fc16d3de37c65fd/action.yml#L15-L18) and will simply build the app. You can control that behavior with the `release` parameter.

What I have in the README is simply a sample workflow of how the action could be used. Have a look at [this](https://github.com/samuelmeuli/action-electron-builder#usage) section: In the sample workflow, GitHub Actions will set the `release` parameter to `true` if a matching Git tag is found, and otherwise it will be set to `false`. So if you'd like to create a release with the sample workflow, you'll need to create a tag as described in the README.

Hope this helps :)

**Comment by vitalykarasik** [comment]
Got it, thank you!
